source:
  paths:
    - projet 1: /Users/denis/prj/simple-backup/env/data/folder-1
    - projet 2: /Users/denis/prj/simple-backup/env/data/folder-2
  exclude:
    - ".ignore"
    - "ignore"

target:
  path: /Users/denis/prj/simple-backup/env/data/out
  purge-after: 180

compressed: false

tools:
  zip: C:/Program Files/7-Zip/7z