source:
  paths:
    - super projet 1: C:/Users/denis/wks-tools/simple-backup/env/data/folder-1
    - super projet 2: C:/Users/denis/wks-tools/simple-backup/env/data/folder-2
  exclude:
    - aa
    - bb

target:
  path: E:/tmp
  purge-after: 180

#compressed: true

tools:
  zip: C:/Program Files/7-Zip/7z