source:
  paths:
    - projet 1: /Users/denis/prj/simple-backup/env/data/folder-1
    - projet 2: /Users/denis/prj/simple-backup/env/data/folder-2
  exclude:
    - "*.mkv"
    - "*.jar"

target:
  path: /Users/denis/prj/simple-backup/env/data/out
  purge-after: 180

compressed: true

tools:
  zip: C:/Program Files/7-Zip/7z