source:
  paths:
    - wks-one: E:/tmp/wks-one
    - wks-steeple: E:/tmp/wks-steeple
  exclude:
    - to_be_ignored
    - ".ignore"
    - ".git"
    - target

target:
  path: E:/tmp
  purge-after: 1

max_size: 500

#compressed: true

tools:
  zip: C:/Program Files/7-Zip/7z